tunnel: jenkins-tunnel
credentials-file: /etc/cloudflared/jenkins-tunnel.json

ingress:
  - hostname: jenkins.rising-shop-dg.com
    service: http://host.docker.internal:8080
  - service: http_status:404