version: "3.8"

services:
  cloudflared:
    build: .
    container_name: cloudflared-jenkins
    restart: always
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml
      - ./jenkins-tunnel.json:/etc/cloudflared/jenkins-tunnel.json
    command: tunnel run


